apiVersion: v1
kind: Namespace
metadata:
  name: tech-local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noir-fashion
  namespace: tech-local
  labels:
    app: noir-fashion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noir-fashion
  template:
    metadata:
      labels:
        app: noir-fashion
    spec:
      containers:
        - name: noir-fashion
          image: nginx:stable-alpine    # substitua pela sua imagem real se quiser
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: noir-fashion
  namespace: tech-local
  labels:
    app: noir-fashion
spec:
  type: NodePort
  selector:
    app: noir-fashion
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
